  data:extend({{
    type = "item",
    name = "uber-transport-belt",
    icon = "__BeltsPlusPlus__/graphics/uber.png",
    icon_size = 32,
    flags = {"goes-to-quickbar"},
    order = "b[steam-power]-a[boiler-2]",
    place_result = "uber-transport-belt",
    stack_size = 50,
  },
  {
    type = "item",
    name = "uber-underground-belt",
    icon = "__BeltsPlusPlus__/graphics/uber.png",
    icon_size = 32,
    flags = {"goes-to-quickbar"},
    order = "b[steam-power]-a[boiler-2]",
    place_result = "uber-underground-belt",
    stack_size = 50,
  },
  {
    type = "item",
    name = "uber-splitter",
    icon = "__BeltsPlusPlus__/graphics/uber.png",
    icon_size = 32,
    flags = {"goes-to-quickbar"},
    order = "b[steam-power]-a[boiler-2]",
    place_result = "uber-splitter",
    stack_size = 50,
  }})